export enum TransactionStatus {
  OFFRE_ACCEPTEE = "OFFRE_ACCEPTEE",
  VERIFICATION_GEOMETRE = "VERIFICATION_GEOMETRE",
  VERIFICATION_NOTAIRE = "VERIFICATION_NOTAIRE",
  SIGNATURE_COMPROMIS = "SIGNATURE_COMPROMIS",
  PAIEMENT = "PAIEMENT",
  TERMINEE = "TERMINEE",
  ANNULEE = "ANNULEE",
}
